export type ProviderKey =
  | "lovable"
  | "openrouter"
  | "groq"
  | "cerebras"
  | "mistral"
  | "google"
  | "cohere"
  | "qwen"
  | "huggingface"
  | "bazaarlink"
  | "cloudflare";

/** Model ids are stored as plain text in the DB, so keep this a string union-ish alias. */
export type CodexModelId = string;

export interface CodexModel {
  id: CodexModelId;
  name: string;
  tagline: string;
  tags: string[];
  cost: number;
  /** Which upstream API serves this model. */
  providerKey: ProviderKey;
  /** The upstream model identifier. */
  provider: string;
  thinking: boolean;
  /** Whether the upstream model reliably supports function/tool calling. */
  tools: boolean;
  /** Native image understanding. Non-vision models get OCR pre-processing instead. */
  vision: boolean;
  /** Grouping label used by the model picker. */
  group: "Flagship" | "Fast" | "Coding" | "Open source";
  /** Rough speed hint used for the icon in the model picker. */
  speed: "fast" | "balanced" | "deep";
}

export const CODEX_MODELS: CodexModel[] = [
  // ---------- Flagship ----------
  {
    id: "oc-code-max",
    name: "Opencimpco Code Max",
    tagline: "Lovable AI flagship — best multi-file engineering",
    tags: ["Best coding", "Multi-file", "Architecture"],
    cost: 400,
    providerKey: "lovable",
    provider: "google/gemini-3.1-pro-preview",
    thinking: true,
    tools: true,
    vision: true,
    group: "Flagship",
    speed: "deep",
  },
  {
    id: "oc-gpt",
    name: "Opencimpco GPT",
    tagline: "GPT-5.4 via Lovable AI for tricky logic",
    tags: ["Reasoning", "Debugging", "Refactors"],
    cost: 350,
    providerKey: "lovable",
    provider: "openai/gpt-5.4",
    thinking: true,
    tools: true,
    vision: true,
    group: "Flagship",
    speed: "deep",
  },
  {
    id: "oc-gpt-sol",
    name: "Opencimpco GPT Sol",
    tagline: "GPT-5.6 Sol — hardest agentic and architecture work",
    tags: ["Frontier", "Agentic", "Long tasks"],
    cost: 450,
    providerKey: "lovable",
    provider: "openai/gpt-5.6-terra",
    thinking: true,
    tools: true,
    vision: true,
    group: "Flagship",
    speed: "deep",
  },

  // ---------- Fast ----------
  {
    id: "oc-code",
    name: "Opencimpco Code",
    tagline: "Lovable AI default — fast, strong full-stack coding",
    tags: ["Balanced", "React", "Streaming"],
    cost: 120,
    providerKey: "lovable",
    provider: "google/gemini-3.6-flash",
    thinking: true,
    tools: true,
    vision: true,
    group: "Fast",
    speed: "fast",
  },
  {
    id: "oc-code-lite",
    name: "Opencimpco Code Lite",
    tagline: "Gemini 3.5 Flash — cheap everyday iterations",
    tags: ["Cheap", "Quick fixes", "High volume"],
    cost: 60,
    providerKey: "lovable",
    provider: "google/gemini-3.5-flash",
    thinking: true,
    tools: true,
    vision: true,
    group: "Fast",
    speed: "fast",
  },
  {
    id: "cerebras-oss120b",
    name: "Opencimpco Turbo",
    tagline: "GPT-OSS 120B on Cerebras — insanely fast",
    tags: ["Fastest", "Quick fixes", "HTML / CSS / JS"],
    cost: 80,
    providerKey: "cerebras",
    provider: "gpt-oss-120b",
    thinking: true,
    tools: true,
    vision: false,
    group: "Fast",
    speed: "fast",
  },
  {
    id: "groq-oss120b",
    name: "Opencimpco Flash",
    tagline: "GPT-OSS 120B on Groq with web search",
    tags: ["Fast", "Tools", "Everyday code"],
    cost: 80,
    providerKey: "groq",
    provider: "openai/gpt-oss-120b",
    thinking: true,
    tools: true,
    vision: false,
    group: "Fast",
    speed: "fast",
  },
  {
    id: "groq-kimi-k2",
    name: "Kimi K2 (Groq)",
    tagline: "Agentic MoE model, very fast tool use",
    tags: ["Agentic", "Tools", "Long code"],
    cost: 100,
    providerKey: "groq",
    provider: "moonshotai/kimi-k2-instruct-0905",
    thinking: true,
    tools: true,
    vision: false,
    group: "Fast",
    speed: "fast",
  },

  // ---------- Coding ----------
  {
    id: "qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    tagline: "Alibaba's flagship coder on Qwen Cloud",
    tags: ["Whole repos", "Agentic", "Refactors"],
    cost: 140,
    providerKey: "qwen",
    provider: "qwen3-coder-plus",
    thinking: true,
    tools: true,
    vision: false,
    group: "Coding",
    speed: "balanced",
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    tagline: "Qwen's largest reasoning model",
    tags: ["Reasoning", "Architecture", "Long context"],
    cost: 160,
    providerKey: "qwen",
    provider: "qwen3-max",
    thinking: true,
    tools: true,
    vision: false,
    group: "Coding",
    speed: "deep",
  },
  {
    id: "qwen-vl-max",
    name: "Qwen VL Max",
    tagline: "Qwen vision model — screenshots to code",
    tags: ["Vision", "OCR", "Screenshot → UI"],
    cost: 140,
    providerKey: "qwen",
    provider: "qwen-vl-max",
    thinking: true,
    tools: true,
    vision: true,
    group: "Coding",
    speed: "balanced",
  },
  {
    id: "qwen3-coder",
    name: "Qwen3 Coder",
    tagline: "Specialised code model, great at whole files",
    tags: ["Code", "Node & Python", "APIs"],
    cost: 100,
    providerKey: "openrouter",
    provider: "qwen/qwen3-coder",
    thinking: true,
    tools: true,
    vision: false,
    group: "Coding",
    speed: "balanced",
  },
  {
    id: "codestral",
    name: "Codestral",
    tagline: "Mistral's dedicated coding model",
    tags: ["Code", "Completion", "Refactors"],
    cost: 100,
    providerKey: "mistral",
    provider: "codestral-latest",
    thinking: true,
    tools: true,
    vision: false,
    group: "Coding",
    speed: "fast",
  },
  {
    id: "mistral-medium",
    name: "Mistral Medium 3",
    tagline: "Balanced Mistral model with vision",
    tags: ["Vision", "Balanced", "Docs"],
    cost: 110,
    providerKey: "mistral",
    provider: "mistral-medium-latest",
    thinking: true,
    tools: true,
    vision: true,
    group: "Coding",
    speed: "balanced",
  },

  // ---------- Open source ----------
  {
    id: "nemotron-super",
    name: "Nemotron 3 Super",
    tagline: "NVIDIA reasoning + coding, free tier",
    tags: ["Thinking", "React", "Refactoring"],
    cost: 120,
    providerKey: "openrouter",
    provider: "nvidia/nemotron-3-super-120b-a12b:free",
    thinking: true,
    tools: false,
    vision: false,
    group: "Open source",
    speed: "balanced",
  },
  {
    id: "nemotron-ultra-550b",
    name: "Nemotron Ultra 550B",
    tagline: "NVIDIA Nemotron 3 Ultra 550B — the largest open reasoning model",
    tags: ["550B", "Frontier", "Architecture"],
    cost: 200,
    providerKey: "openrouter",
    provider: "nvidia/nemotron-3-ultra-550b-a55b",
    thinking: true,
    tools: true,
    vision: false,
    group: "Open source",
    speed: "deep",
  },
  {
    id: "nemotron-ultra",
    name: "Nvidia Nemotron Ultra",
    tagline: "Nemotron Ultra 253B — deep reasoning, huge context",
    tags: ["Ultra", "Thinking", "Architecture"],
    cost: 160,
    providerKey: "openrouter",
    provider: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    thinking: true,
    tools: false,
    vision: false,
    group: "Open source",
    speed: "deep",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3.2",
    tagline: "Strong open reasoning model at low cost",
    tags: ["Reasoning", "Cheap", "Code"],
    cost: 90,
    providerKey: "openrouter",
    provider: "deepseek/deepseek-chat-v3.1",
    thinking: true,
    tools: true,
    vision: false,
    group: "Open source",
    speed: "balanced",
  },
  {
    id: "glm-4-6",
    name: "GLM 4.6",
    tagline: "Zhipu's coding-focused open model",
    tags: ["Code", "Agentic", "Long context"],
    cost: 100,
    providerKey: "openrouter",
    provider: "z-ai/glm-4.6",
    thinking: true,
    tools: true,
    vision: false,
    group: "Open source",
    speed: "balanced",
  },
  {
    id: "llama4-maverick",
    name: "Llama 4 Maverick",
    tagline: "Meta's multimodal MoE via OpenRouter",
    tags: ["Vision", "Fast", "General"],
    cost: 90,
    providerKey: "openrouter",
    provider: "meta-llama/llama-4-maverick",
    thinking: true,
    tools: true,
    vision: true,
    group: "Open source",
    speed: "fast",
  },
  {
    id: "command-a",
    name: "Cohere Command A",
    tagline: "Cohere's flagship for docs and tooling",
    tags: ["Docs", "Tools", "Long context"],
    cost: 100,
    providerKey: "cohere",
    provider: "command-a-03-2025",
    thinking: true,
    tools: true,
    vision: false,
    group: "Open source",
    speed: "balanced",
  },

  // ---------- Bazaarlink (frontier, verified live) ----------
  {
    id: "bl-deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    tagline: "Bazaarlink frontier reasoning — deep multi-file engineering",
    tags: ["Frontier", "Reasoning", "Multi-file"],
    cost: 260,
    providerKey: "bazaarlink",
    provider: "deepseek-v4-pro",
    thinking: true,
    tools: true,
    vision: false,
    group: "Flagship",
    speed: "deep",
  },
  {
    id: "bl-qwen37-max",
    name: "Qwen 3.7 Max",
    tagline: "Bazaarlink's largest Qwen — architecture and long context",
    tags: ["Long context", "Architecture", "Code"],
    cost: 220,
    providerKey: "bazaarlink",
    provider: "qwen3.7-max",
    thinking: true,
    tools: true,
    vision: false,
    group: "Flagship",
    speed: "deep",
  },
  {
    id: "bl-grok-build",
    name: "Grok Build",
    tagline: "Build-tuned Grok — great at shipping whole apps",
    tags: ["App builder", "Agentic", "Fast"],
    cost: 180,
    providerKey: "bazaarlink",
    provider: "grok-build-0.1",
    thinking: true,
    tools: true,
    vision: false,
    group: "Flagship",
    speed: "balanced",
  },
  {
    id: "bl-kimi-k27-code",
    name: "Kimi K2.7 Code",
    tagline: "Code-specialised Kimi — surgical diffs and refactors",
    tags: ["Code", "Diffs", "Refactors"],
    cost: 150,
    providerKey: "bazaarlink",
    provider: "kimi-k2.7-code",
    thinking: true,
    tools: true,
    vision: false,
    group: "Coding",
    speed: "balanced",
  },
  {
    id: "bl-glm-52",
    name: "GLM 5.2",
    tagline: "Zhipu GLM 5.2 — strong agentic front-end work",
    tags: ["Agentic", "UI", "Long context"],
    cost: 140,
    providerKey: "bazaarlink",
    provider: "glm-5.2",
    thinking: true,
    tools: true,
    vision: false,
    group: "Coding",
    speed: "balanced",
  },

  // ---------- Vision + Cloudflare edge ----------
  {
    id: "qwen36-groq",
    name: "Qwen 3.6 27B (Groq)",
    tagline: "Groq-hosted Qwen 3.6 — instant everyday coding",
    tags: ["Fastest", "Quick fixes", "Tools"],
    cost: 70,
    providerKey: "groq",
    provider: "qwen/qwen3.6-27b",
    thinking: true,
    tools: true,
    vision: false,
    group: "Fast",
    speed: "fast",
  },
  {
    id: "cf-llama4-scout",
    name: "Llama 4 Scout (Edge)",
    tagline: "Cloudflare Workers AI — vision on the edge",
    tags: ["Vision", "Edge", "Cheap"],
    cost: 60,
    providerKey: "cloudflare",
    provider: "@cf/meta/llama-4-scout-17b-16e-instruct",
    thinking: true,
    tools: true,
    vision: true,
    group: "Open source",
    speed: "fast",
  },
  {
    id: "cf-llama33-70b",
    name: "Llama 3.3 70B (Edge)",
    tagline: "Cloudflare fp8-fast Llama 3.3 — reliable everyday coding",
    tags: ["Edge", "Fast", "General"],
    cost: 60,
    providerKey: "cloudflare",
    provider: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    thinking: true,
    tools: true,
    vision: false,
    group: "Open source",
    speed: "fast",
  },
];

export const MODEL_GROUPS = ["Flagship", "Fast", "Coding", "Open source"] as const;

export const DEFAULT_MODEL_ID = "oc-code";

export function getModel(id: string): CodexModel {
  return (
    CODEX_MODELS.find((m) => m.id === id) ??
    CODEX_MODELS.find((m) => m.id === DEFAULT_MODEL_ID) ??
    CODEX_MODELS[0]
  );
}
